export const booksData = [
  {
    id: 1,
    bookName: 'JavaScript & jQuery:',
    img: 'https://media.wiley.com/product_data/coverImage300/34/11190386/1119038634.jpg',
    price: 15.99,
    rating: 5,
    author: 'Jon Duckett',
    publicationYear: 2014,
    isFavorite: true,
  },
  {
    id: 2,
    bookName: 'HTML & CSS',
    img: 'https://preview.redd.it/m14hlniqyfz41.jpg?auto=webp&s=c18532cb4636a2dcb9d36748e461bb5794d3cfd4',
    price: 12.99,
    rating: 3,
    author: 'David DuRocher',
    publicationYear: 2016,
    isFavorite: false,
  },
  {
    id: 3,
    bookName: 'React.Js',
    img: 'https://avatars.githubusercontent.com/u/32949016?s=280&v=4',
    price: 14.99,
    rating: 4,
    author: 'J.D. Salinger',
    publicationYear: 2018,
    isFavorite: true,
  },
  {
    id: 4,
    bookName: 'Node.js',
    img: 'https://static-01.daraz.com.bd/p/095d16fa530fde09748d73d320dbfdfc.jpg',
    price: 11.99,
    rating: 4,
    author: 'Mario Casciaro',
    publicationYear: 2020,
    isFavorite: false,
  },
  {
    id: 5,
    bookName: 'Python',
    img: 'https://m.media-amazon.com/images/I/418ow0JdGSL.jpg',
    price: 19.99,
    rating: 5,
    author: 'Mark Lutz',
    publicationYear: 2021,
    isFavorite: false,
  },
  {
    id: 6,
    bookName: 'PHP & MySQL',
    img: 'https://m.media-amazon.com/images/I/71BFM1G4iBL._AC_UF1000,1000_QL80_.jpg',
    price: 16.99,
    rating: 5,
    author: 'Kevin Yank',
    publicationYear: 2010,
    isFavorite: false,
  },
  {
    id: 7,
    bookName: 'C#',
    img: 'https://m.media-amazon.com/images/I/41-mFa9UU0L.jpg',
    price: 13.99,
    rating: 4,
    author: 'Jane Austen',
    publicationYear: 2022,
    isFavorite: false,
  },
  {
    id: 8,
    bookName: 'Express.js',
    img: 'https://freecomputerbooks.com/covers/Express.js-Guide.jpg',
    price: 18.99,
    rating: 5,
    author: 'Dan Brown',
    publicationYear: 2019,
    isFavorite: true,
  },
]
